export const RECEIVE_NAVBAR = 'RECEIVE_NAVBAR';
export const RECEIVE_HEADINGS = 'RECEIVE_HEADINGS';
export const RECEIVE_EXPERIENCES = 'RECEIVE_EXPERIENCES';
export const RECEIVE_SKILLS = 'RECEIVE_SKILLS';
export const RECEIVE_PROJECTS = 'RECEIVE_PROJECTS';
export const RECEIVE_CONTACTS = 'RECEIVE_CONTACTS';